# Generated by Django 4.1.7 on 2023-04-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materia', models.TextField(max_length=30)),
                ('descrpcion', models.TextField(max_length=100)),
                ('estado', models.TextField(default='por hacer', verbose_name=20)),
            ],
        ),
    ]
