# Generated by Django 4.1.7 on 2023-04-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercera', '0002_personas'),
    ]

    operations = [
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='personas',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='personas',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
