# Generated by Django 4.1.7 on 2023-04-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tercera', '0004_rename_descrpcion_materias_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
